package fields

// All possible fields for Option
const (
	OptionSymbol                 = "0"
	OptionDescription            = "1"
	OptionBidPrice               = "2"
	OptionAskPrice               = "3"
	OptionLastPrice              = "4"
	OptionHighPrice              = "5"
	OptionLowPrice               = "6"
	OptionClosePrice             = "7"
	OptionTotalVolume            = "8"
	OptionOpenInterest           = "9"
	OptionVolatility             = "10"
	OptionQuoteTime              = "11"
	OptionTradeTime              = "12"
	OptionMoneyIntrinsicValue    = "13"
	OptionQuoteDay               = "14"
	OptionTradeDay               = "15"
	OptionExpirationYear         = "16"
	OptionMultiplier             = "17"
	OptionDigits                 = "18"
	OptionOpenPrice              = "19"
	OptionBidSize                = "20"
	OptionAskSize                = "21"
	OptionLastSize               = "22"
	OptionNetChange              = "23"
	OptionStrikePrice            = "24"
	OptionContractType           = "25"
	OptionUnderlying             = "26"
	OptionExpirationMonth        = "27"
	OptionDeliverables           = "28"
	OptionTimeValue              = "29"
	OptionExpirationDay          = "30"
	OptionDaystoExpiration       = "31"
	OptionDelta                  = "32"
	OptionGamma                  = "33"
	OptionTheta                  = "34"
	OptionVega                   = "35"
	OptionRho                    = "36"
	OptionSecurityStatus         = "37"
	OptionTheoreticalOptionValue = "38"
	OptionUnderlyingPrice        = "39"
	OptionUVExpirationType       = "40"
	OptionMark                   = "41"
)
