package quotes

type ETF struct {
	AssetType                          string  `json:"assetType"`
	AssetMainType                      string  `json:"assetMainType"`
	CUSIP                              string  `json:"cusip"`
	AssetSubType                       string  `json:"assetSubType"`
	Symbol                             string  `json:"symbol"`
	Description                        string  `json:"description"`
	BidPrice                           float32 `json:"bidprice"`
	BidSize                            float32 `json:"bidSize"`
	BidID                              string  `json:"bidId"`
	AskPrice                           float32 `json:"askPrice"`
	AskSize                            float32 `json:"askSize"`
	AskID                              string  `json:"askID"`
	LastPrice                          float32 `json:"lastPrice"`
	LastSize                           int     `json:"lastSize"`
	LastID                             string  `json:"lastId"`
	OpenPrice                          float32 `json:"openPrice"`
	HighPrice                          float32 `json:"highPrice"`
	LowPrice                           float32 `json:"lowPrice"`
	BidTick                            string  `json:"bidTick"`
	ClosePrice                         float32 `json:"closePrice"`
	NetChange                          int     `json:"netChange"`
	TotalVolume                        int     `json:"totalVolume"`
	QuoteTimeInLong                    int     `json:"quoteTimeInLong"`
	TradeTimeInLong                    int     `json:"tradeTimeInLong"`
	Mark                               float32 `json:"mark"`
	Exchange                           string  `json:"exchange"`
	ExchangeName                       string  `json:"exchangeName"`
	Marginable                         bool    `json:"marginable"`
	Shortable                          bool    `json:"shortable"`
	Volatility                         float32 `json:"volatility"`
	Digits                             int     `json:"digits"`
	YearHigh                           float32 `json:"52WkHigh"`
	YearLow                            float32 `json:"52WkLow"`
	NAV                                int     `json:"nAV"`
	PERatio                            float32 `json:"peRatio"`
	DivAmount                          float32 `json:"divAmount"`
	DivYield                           float32 `json:"divYield"`
	DivDate                            string  `json:"divDate"`
	SecurityStatus                     string  `json:"securityStatus"`
	RegularMarketLastPrice             float32 `json:"regularMarketLastPrice"`
	RegularMarketLastSize              int     `json:"regularMarketLastSize"`
	RegularMarketNetChange             float32 `json:"regularMarketNetChange"`
	RegularMarketTradeTimeInLong       int     `json:"regularMarketTradeTimeInLong"`
	NetPercentChangeInDouble           float32 `json:"netPercentChangeInDouble"`
	MarkChangeInDouble                 float32 `json:"markChangeInDouble"`
	MarkPercentChangeInDouble          float32 `json:"markPercentChangeInDouble"`
	RegularMarketPercentChangeInDouble float32 `json:"regularMarketPercentChangeInDouble"`
	IsDelayed                          bool    `json:"delayed"`
}
